mp3finder review
mikhail-akimov/LearnPython pull request #6
Opened 2018-10-16 13:02 UTC by mikhail-akimov

2018-10-16 13:13 UTC, mhanygin requested changes

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +        if key == 'disc_total' and song_info_dict[key]:
else if

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +        if key == 'disc_total' and song_info_dict[key]:
далее аналогично

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +    return result
return [track  for track in collection if track['artist'] == artist]

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +            discography[key] = sorted(discography[key],
сортировка дорогая операция, не надо делать ее каждый раз

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +        print('{} ({})'.format(album, discography[album][0]['year']))
если собираешься работать с сущностью много, лучше сохранить ее в локальную переменную, так доступ будет быстрее

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +        info['path'] = track
почему track не прокидывать в path внутри get_song_info_from_mp3_tags, так будет удобнее всем

2018-10-16 13:13 UTC, mhanygin commented on Devman/mp3finder.py
> +        info['path'] = track
функция станет вида return [get_song_info_from_mp3_tags(track) for track in tracks]

2018-10-16 14:17 UTC, mikhail-akimov commented on Devman/mp3finder.py
> +        if key == 'disc_total' and song_info_dict[key]:
В данный цикл у меня приходит словарь {'disc': '1', 'disc_total': '1', 'track': '3', 'year': '2008'}. 

Если я использую elif, то разве обработка не ограничится одним условием?

2018-10-16 14:21 UTC, mikhail-akimov commented on Devman/mp3finder.py
> +        info['path'] = track
Я допихиваю в словарь каждого трэка ещё ключ 'path' и ссылку в его значение. Не могу понять, смогу ли я так в скоращённой форме.

2018-10-16 14:23 UTC, mikhail-akimov commented on Devman/mp3finder.py
> +        print('{} ({})'.format(album, discography[album][0]['year']))
Ты имеешь ввиду сущность discography[album]?

2018-10-16 14:27 UTC, mikhail-akimov commented on Devman/mp3finder.py
> +            discography[key] = sorted(discography[key],
Поднял сортировку на 1 цикл выше.

2018-10-16 14:39 UTC, mhanygin commented on Devman/mp3finder.py
> +        info['path'] = track
ты передаешь track в функцию, допихивай там

2018-10-16 14:39 UTC, mhanygin commented on Devman/mp3finder.py
> +        if key == 'disc_total' and song_info_dict[key]:
ограничится первым нормальным if, остальные проигнорятся, а разве не так надо?

2018-10-16 14:39 UTC, mhanygin commented on Devman/mp3finder.py
> +        print('{} ({})'.format(album, discography[album][0]['year']))
да

2018-10-16 14:40 UTC, mhanygin approved these changes

2018-10-16 14:44 UTC, mikhail-akimov commented on Devman/mp3finder.py
> +        if key == 'disc_total' and song_info_dict[key]:
Подожди, вот у меня {'disc': '1', 'disc_total': '1', 'track': '3', 'year': '2008'}. Любые из этих значений (или даже все) могу быть None. Разве можно в один if по всем провериться и заменить? Я что-то туплю.

Я такую портянку развернул из-за того, что нельзя NoneType в int конвертировать.

2018-10-17 07:23 UTC, mikhail-akimov commented on Devman/mp3finder.py
> +        info['path'] = track
Долго тупил, но всё оказалось просто :)

2018-10-17 08:22 UTC, merged